### ISSUE TITLE
memory error when using gpu

### ISSUE THREAD

**Issue by kiyaya** [anlthms/dsb-2017#10]
Hi, I encounter the memory error at first epoch with GPU enabled. By monitoring with top & nvidia-smi, it seems GPU memory is enough but CPU memory is exhausted quickly. I checked with running epoch with GPU disabled (use CPU), the first 1 epoch starts normally but just too slow to continue.

The error output is:
`  BatchNorm Layer 'Convolution_10_bnorm': 1024 inputs, 1 steps, 1024 feature maps
  Activation Layer 'Convolution_10_Rectlin': Rectlin
  Dropout Layer 'Dropout_0': 1024 inputs and outputs, keep 50% (caffe_compat False)
  Linear Layer 'Linear_0': 1024 inputs, 2 outputs
  BatchNorm Layer 'Linear_0_bnorm': 2 inputs, 1 steps, 2 feature maps
  Activation Layer 'Linear_0_Softmax': Softmax
Traceback (most recent call last):
  File "./run.py", line 94, in <module>
    model.fit(train, optimizer=opt, num_epochs=args.epochs, cost=cost, callbacks=callbacks)
  File "/home/xx/neon/neon/models/model.py", line 182, in fit
    self._epoch_fit(dataset, callbacks)
  File "/home/xx/neon/neon/models/model.py", line 204, in _epoch_fit
    x = self.fprop(x)
  File "/home/xx/neon/neon/models/model.py", line 235, in fprop
    return self.layers.fprop(x, inference)
  File "/home/xx/neon/neon/layers/container.py", line 332, in fprop
    x = l.fprop(x, inference=inference)
  File "/home/xx/neon/neon/layers/layer.py", line 798, in fprop
    bsum=self.batch_sum)
  File "/home/xx/neon/neon/backends/nervanagpu.py", line 1982, in fprop_conv
    layer.fprop_kernels.bind_params(I, F, O, X, bias, bsum, alpha, beta, relu, brelu, slope)
  File "/home/xx/neon/neon/backends/convolution.py", line 541, in bind_params
    bsum_data, x_data = self.xprop_params(O, X, bias, bsum, beta, relu, brelu, slope)
  File "/home/xx/neon/neon/backends/convolution.py", line 77, in xprop_params
    bsum_data = self.bsum.bind_params(bsum)
  File "/home/xx/neon/neon/backends/convolution.py", line 1051, in bind_params
    bsum_data      = self.lib.scratch_buffer_offset(self.size)
  File "/home/xx/neon/neon/backends/nervanagpu.py", line 875, in scratch_buffer_offset
    data = int(_get_scratch_data(self.scratch_size)) + self.scratch_offset
  File "<decorator-gen-60>", line 2, in _get_scratch_data
  File "/home/xx/neon/.venv2/local/lib/python2.7/site-packages/pycuda/tools.py", line 430, in context_dependent_memoize
    result = func(*args)
  File "/home/xx/neon/neon/backends/nervanagpu.py", line 3195, in _get_scratch_data
    return drv.mem_alloc(scratch_size)
pycuda._driver.MemoryError: cuMemAlloc failed: out of memory`

Shouldn't pycuda.driver.mem_alloc allocate memory from GPU? But why CPU memory exhausted? Is it a bug or something I missed?

**Comment by kiyaya** [comment]
OK, I just read the code and decreased the batch-size by parameter -z. Now it is working.
