### ISSUE TITLE
memory error on run.py?

### ISSUE THREAD

**Issue by galactica147** [anlthms/dsb-2017#2]
I'm testing run.py (training) with a toy-size subset, say 24 samples in total from luna16. So there are 18 for training and 6 for validation (testing). The rest settings are by default. 

`./run.py -e 6 -w luna/vids -r 0 -v -eval 1 -s model.pkl`

The output looks like the following: 

```
Network Layers:
Sequential
  Convolution Layer 'Convolution_0': 1 x (64x64x64) inputs, 16 x (29x29x29) outputs, 1,1,1 padding, 2,2,2 stride, 1,1,1 dilation
  Activation Layer 'Convolution_0_Rectlin': Rectlin
  Convolution Layer 'Convolution_1': 16 x (29x29x29) inputs, 32 x (21x21x21) outputs, 0,0,0 padding, 1,1,1 stride, 2,2,2 dilation
  BatchNorm Layer 'Convolution_1_bnorm': 296352 inputs, 1 steps, 32 feature maps
  Activation Layer 'Convolution_1_Rectlin': Rectlin
  Convolution Layer 'Convolution_2': 32 x (21x21x21) inputs, 64 x (17x17x17) outputs, 0,0,0 padding, 1,1,1 stride, 2,2,2 dilation
  BatchNorm Layer 'Convolution_2_bnorm': 314432 inputs, 1 steps, 64 feature maps
  Activation Layer 'Convolution_2_Rectlin': Rectlin
  Pooling Layer 'Pooling_0': 64 x (17x17) inputs, 64 x (9x9) outputs
  Convolution Layer 'Convolution_3': 64 x (9x9x9) inputs, 128 x (8x8x8) outputs, 0,0,0 padding, 1,1,1 stride, 1,1,1 dilation
  BatchNorm Layer 'Convolution_3_bnorm': 65536 inputs, 1 steps, 128 feature maps
  Activation Layer 'Convolution_3_Rectlin': Rectlin
  Convolution Layer 'Convolution_4': 128 x (8x8x8) inputs, 128 x (7x7x7) outputs, 0,0,0 padding, 1,1,1 stride, 1,1,1 dilation
  BatchNorm Layer 'Convolution_4_bnorm': 43904 inputs, 1 steps, 128 feature maps
  Activation Layer 'Convolution_4_Rectlin': Rectlin
  Convolution Layer 'Convolution_5': 128 x (7x7x7) inputs, 128 x (6x6x6) outputs, 0,0,0 padding, 1,1,1 stride, 1,1,1 dilation
  BatchNorm Layer 'Convolution_5_bnorm': 27648 inputs, 1 steps, 128 feature maps
  Activation Layer 'Convolution_5_Rectlin': Rectlin
  Convolution Layer 'Convolution_6': 128 x (6x6x6) inputs, 256 x (5x5x5) outputs, 0,0,0 padding, 1,1,1 stride, 1,1,1 dilation
  BatchNorm Layer 'Convolution_6_bnorm': 32000 inputs, 1 steps, 256 feature maps
  Activation Layer 'Convolution_6_Rectlin': Rectlin
  Convolution Layer 'Convolution_7': 256 x (5x5x5) inputs, 1024 x (4x4x4) outputs, 0,0,0 padding, 1,1,1 stride, 1,1,1 dilation
  BatchNorm Layer 'Convolution_7_bnorm': 65536 inputs, 1 steps, 1024 feature maps
  Activation Layer 'Convolution_7_Rectlin': Rectlin
  Convolution Layer 'Convolution_8': 1024 x (4x4x4) inputs, 4096 x (3x3x3) outputs, 0,0,0 padding, 1,1,1 stride, 1,1,1 dilation
  BatchNorm Layer 'Convolution_8_bnorm': 110592 inputs, 1 steps, 4096 feature maps
  Activation Layer 'Convolution_8_Rectlin': Rectlin
  Convolution Layer 'Convolution_9': 4096 x (3x3x3) inputs, 2048 x (2x2x2) outputs, 0,0,0 padding, 1,1,1 stride, 1,1,1 dilation
  BatchNorm Layer 'Convolution_9_bnorm': 16384 inputs, 1 steps, 2048 feature maps
  Activation Layer 'Convolution_9_Rectlin': Rectlin
  Convolution Layer 'Convolution_10': 2048 x (2x2x2) inputs, 1024 x (1x1) outputs, 0,0,0 padding, 1,1,1 stride, 1,1,1 dilation
  BatchNorm Layer 'Convolution_10_bnorm': 1024 inputs, 1 steps, 1024 feature maps
  Activation Layer 'Convolution_10_Rectlin': Rectlin
  Dropout Layer 'Dropout_0': 1024 inputs and outputs, keep 50% (caffe_compat False)
  Linear Layer 'Linear_0': 1024 inputs, 2 outputs
  BatchNorm Layer 'Linear_0_bnorm': 2 inputs, 1 steps, 2 feature maps
  Activation Layer 'Linear_0_Softmax': Softmax
Traceback (most recent call last):
File "./run.py", line 94, in <module>
    model.fit(train, optimizer=opt, num_epochs=args.epochs, cost=cost, callbacks=callbacks)
  File "/pyenv/lib/python2.7/site-packages/neon-1.8.2-py2.7.egg/neon/models/model.py", line 182, in fit
    self._epoch_fit(dataset, callbacks)
  File "/pyenv/lib/python2.7/site-packages/neon-1.8.2-py2.7.egg/neon/models/model.py", line 200, in _epoch_fit
    for mb_idx, (x, t) in enumerate(dataset):
  File "/dsb-2017/data.py", line 131, in __iter__
    yield self.next_minibatch(start)
  File "/dsb-2017/data.py", line 96, in next_minibatch
    self.next_macrobatch()
  File "/dsb-2017/data.py", line 88, in next_macrobatch
    self.shuffle(self.data, self.targets)
  File "/luna16/dsb-2017/data.py", line 214, in shuffle
    data[:] = data[inds]
MemoryError
```

Is this error due to the small # of samples for training? 
If so, what's the minimum of samples required for training? 

'convert.py' takes too long to process the whole luna16 dataset, so just wanted to make sure neon take handle a subset of it properly. 

Please advise. 
Thanks!

**Comment by galactica147** [comment]
it's probably due to the abortion of running convert.py, during which only incomplete data is written into files. re-running convert.py solved this issue. closing.
